import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from shiny import App, render, ui, reactive
sns.set_theme(style='dark')
df = pd.read_csv('attendance_anonymised-1.csv')
df = df.drop('Planned End Date', axis=1) # Drops Planned End Date, axis=1 means it drops a column
df = df.rename(columns={'Person Code': 'Person Code', 'Unit Instance Code': 'Module Code', 'Calocc Code': 'Year', 
                   'Surname': 'Surname', 'Forename': 'Forename', 'Long Description': 'Module Name', 'Register Event ID': 'Event ID',
                   'Object ID': 'Object ID', 'Register Event Slot ID': 'Event Slot ID', 'Planned Start Date': 'Date', 
                   'is Positive': 'Has Attended', 'Postive Marks': 'Attended', 'Negative Marks': 'NotAttended',
                   'Usage Code': 'Attendance Code'}) # Rename method to change column names
df['Date'] = pd.to_datetime(df['Date']) # Datetime method on 'Date' column
df = df[df['Module Name'] != 'Epidemiology'].copy() # Removes Epidemiology
Module_Names = sorted(df['Module Name'].unique().tolist()) # Provides a list of unique values in 
                                                   # the column 'Module Name' and puts them into a list
module_attendance_mean = df.groupby('Module Name')['Attended'].mean()
# UI 
app_ui = ui.page_fluid(
    ui.panel_title('Module Comparison', 'Window title'), # Title of app

    ui.layout_sidebar(
        # The sidebar panel contains inputs 
        ui.sidebar(
            ui.input_select(
                'module_select', # ID that the server uses to read this input's value
                'Select Module:',  # The label displayed to the user
                choices=Module_Names,  # The list of options from the df
            ),            
            ui.output_ui('module_stats_title'),
            ui.output_ui("module_stats"), 
            title='Module Selection and Stats' # Title for the sidebar
        ),
        # Main panel that the plots will go into
        ui.card( 
            ui.card_header('Average Attendance Over Time'),
            ui.output_plot('attendance_plot') # This output will display the plot generated by the server
        )
    )     
)

# Server
def server(input, output, session):
    @reactive.Calc # Fetches, filters and calculates data
    def plot_data():
        selected_module = input.module_select() # Gets the currently selected module
        df_filtered = df[df['Module Name'] == selected_module].copy() # Filters df using selected module variable
        average_attendance = df_filtered.groupby('Date')['Attended'].mean() # Calculates avg attendance by date.
        return average_attendance
    
    @reactive.Calc
    def module_student_numbers(): # Calculates the number of students in a module
        selected_module = input.module_select()
        df_filtered = df[df['Module Name'] == selected_module]
        module_count = df_filtered['Person Code'].value_counts().count() # Counts the number of unique Person codes
        return module_count
    
    @reactive.Calc
    def module_average(): # Function for module average
        selected_module = input.module_select() # Variable for whichever module has been selected
        average = module_attendance_mean.loc[selected_module] # Uses loc method to filter df
        return average
    
    @output
    @render.plot  # Tells Shiny this function will return a plot
    def attendance_plot():
        average_attendance_data = plot_data() # Calls the reactive calc to get the data
        module_name = input.module_select() # Gets module name for title 

        fig, ax = plt.subplots() # Gets the axes and figure objects
        sns.lineplot(data=average_attendance_data)
        ax.set_title(f'Average Attendance for {module_name}') # f string to have a reactive title
        ax.set_xlabel('Date') # axis labels
        ax.set_ylabel('Average Attendance')
        fig.autofmt_xdate() # Fixes the overlapping dates problem I've had.
        return fig
    
    @render.text
    def module_stats(): # Gets the values from the functions and renders them to the UI
        module_student_number = module_student_numbers() 
        avg_percent = (f'{round((module_average() * 100), 1)}%') # Converts to a percentage
        return(
            f'Students Enrolled: {module_student_number}\n'
            f'Overall Module Average: {avg_percent}'
            )
    @render.text # I couldn't find a way to make the spaces work so I added another @render.text
    def module_stats_title():
        return 'Module Statistics'

# Run app
app = App(app_ui, server)